apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: journee-18d23d
  namespace: journee
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: "cloudflare-tunnel"
  rules:
    - host: journee-18d23d.aooba.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: journee-18d23d
                port:
                  number: 80
