apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-f0debe
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: fossa
    path: k8s/manifests-f0debe
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
