apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-e8f974
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: fix-save-feature
    path: k8s/manifests-e8f974
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
