apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-79c33a
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: add-notify
    path: k8s/manifests-79c33a
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
